# Generated by Django 4.0.2 on 2022-02-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atleta',
            old_name='graduação',
            new_name='graduacao',
        ),
    ]
